In [1]:
# Assignment 1
# Student Performance Prediction using Decision Tree

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
df = pd.read_csv("student_performance.csv")

print("Dataset loaded successfully!")
print("Dataset Shape:", df.shape)

df.head()

Dataset loaded successfully!
Dataset Shape: (100, 18)

,StudentID,G1,G2,G3,Mjob,Fjob,age,address,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic
0,1,6,2,2,teacher,at_home,21,rural,3,1,no,yes,yes,yes,yes,yes,no,yes
1,2,19,11,18,health,teacher,18,rural,1,1,no,no,no,no,yes,no,no,no
2,3,14,7,19,health,other,20,urban,1,1,yes,yes,yes,no,no,no,yes,yes
3,4,10,2,6,services,health,21,urban,3,1,yes,no,yes,no,yes,no,no,no
4,5,7,0,19,health,health,18,rural,4,1,no,no,yes,no,yes,yes,yes,no

In [3]:
print("Columns in Dataset:")
print(df.columns)

print("\nMissing Values:")
print(df.isnull().sum())

Columns in Dataset:
Index(['StudentID', 'G1', 'G2', 'G3', 'Mjob', 'Fjob', 'age', 'address',
       'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic'],
      dtype='str')

Missing Values:
StudentID     0
G1            0
G2            0
G3            0
Mjob          0
Fjob          0
age           0
address       0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
dtype: int64

In [4]:
# G3 is the final grade
# G3 >= 10 = Pass (1)
# G3 < 10 = Fail (0)

df["result"] = (df["G3"] >= 10).astype(int)

print(df[["G1", "G2", "G3", "result"]].head(10))

print("\nPass/Fail Count:")
print(df["result"].value_counts())

   G1  G2  G3  result
0   6   2   2       0
1  19  11  18       1
2  14   7  19       1
3  10   2   6       0
4   7   0  19       1
5   6   2   8       0
6  18   4   0       0
7  10  14   7       0
8  10  13   6       0
9   3   2  17       1

Pass/Fail Count:
result
0    54
1    46
Name: count, dtype: int64

In [5]:
X = df[["G1", "G2", "studytime", "failures", "age"]]

y = df["result"]

print("Features:")
print(X.head())

print("\nTarget:")
print(y.head())

Features:
   G1  G2  studytime  failures  age
0   6   2          3         1   21
1  19  11          1         1   18
2  14   7          1         1   20
3  10   2          3         1   21
4   7   0          4         1   18

Target:
0    0
1    1
2    1
3    0
4    1
Name: result, dtype: int64

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Data:", X_train.shape)
print("Testing Data:", X_test.shape)

Training Data: (80, 5)
Testing Data: (20, 5)

In [7]:
depths = [3, 4, 5]

training_accuracies = []
testing_accuracies = []

for depth in depths:

    model = DecisionTreeClassifier(
        max_depth=depth,
        random_state=42
    )

    # Train model
    model.fit(X_train, y_train)

    # Predictions
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)

    # Accuracy
    train_accuracy = accuracy_score(y_train, train_pred)
    test_accuracy = accuracy_score(y_test, test_pred)

    training_accuracies.append(train_accuracy)
    testing_accuracies.append(test_accuracy)

    print("Max Depth:", depth)
    print("Training Accuracy:", train_accuracy)
    print("Testing Accuracy:", test_accuracy)

    print("Confusion Matrix:")
    print(confusion_matrix(y_test, test_pred))

    print("\nClassification Report:")
    print(classification_report(y_test, test_pred))

    print("--------------------------------------")

Max Depth: 3
Training Accuracy: 0.7
Testing Accuracy: 0.4
Confusion Matrix:
[[4 7]
 [5 4]]

Classification Report:
              precision    recall  f1-score   support

           0       0.44      0.36      0.40        11
           1       0.36      0.44      0.40         9

    accuracy                           0.40        20
   macro avg       0.40      0.40      0.40        20
weighted avg       0.41      0.40      0.40        20

--------------------------------------
Max Depth: 4
Training Accuracy: 0.8
Testing Accuracy: 0.45
Confusion Matrix:
[[5 6]
 [5 4]]

Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.45      0.48        11
           1       0.40      0.44      0.42         9

    accuracy                           0.45        20
   macro avg       0.45      0.45      0.45        20
weighted avg       0.45      0.45      0.45        20

--------------------------------------
Max Depth: 5
Training Accuracy: 0.8375
Testing Accuracy: 0.4
Confusion Matrix:
[[5 6]
 [6 3]]

Classification Report:
              precision    recall  f1-score   support

           0       0.45      0.45      0.45        11
           1       0.33      0.33      0.33         9

    accuracy                           0.40        20
   macro avg       0.39      0.39      0.39        20
weighted avg       0.40      0.40      0.40        20

--------------------------------------

In [8]:
comparison = pd.DataFrame({
    "Max Depth": depths,
    "Training Accuracy": training_accuracies,
    "Testing Accuracy": testing_accuracies
})

comparison

   Max Depth  Training Accuracy  Testing Accuracy
0          3             0.7000              0.40
1          4             0.8000              0.45
2          5             0.8375              0.40

In [ ]:
plt.figure(figsize=(8, 5))

plt.plot(
    depths,
    training_accuracies,
    marker="o",
    label="Training Accuracy"
)

plt.plot(
    depths,
    testing_accuracies,
    marker="o",
    label="Testing Accuracy"
)

plt.xlabel("Maximum Depth")
plt.ylabel("Accuracy")
plt.title("Impact of Decision Tree Depth on Model Performance")

plt.xticks(depths)
plt.legend()
plt.grid()

plt.show()